vim.opt.background = 'light'
vim.opt.breakindent = true
vim.opt.clipboard = vim.opt.clipboard + 'unnamedplus'
vim.opt.completeopt = 'menuone,noselect'
vim.opt.expandtab = true
vim.opt.hlsearch = false
vim.opt.ignorecase = true
vim.opt.mouse = 'a'
vim.opt.number = true
vim.opt.rnu = true
vim.opt.shiftwidth = 2
vim.opt.signcolumn = 'yes'
vim.opt.smartcase = true
vim.opt.tabstop = 2
vim.opt.termguicolors = true
vim.opt.undofile = true
vim.opt.updatetime = 250
vim.opt.wrap = true

