#!/bin/zsh

YABAI_SCRIPTS=${HOME}/.config/yabai/scripts
SET_SPACE_LABELS=${YABAI_SCRIPTS}/set_space_labels.zsh
SIMPLE_BAR_REFRESH="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\"'"

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_origin_display        default
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xFF000000
yabai -m config normal_window_border_color   0x00FFFFFF
yabai -m config insert_feedback_color        ff8474
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config external_bar                 all:36:00
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5 
yabai -m config bottom_padding               5 
yabai -m config left_padding                 5  
yabai -m config right_padding                5  
yabai -m config window_gap                   5 

# Turn off management for certain apps
yabai -m rule --add app="^Firefox$"             space=^1
yabai -m rule --add app="^Safari$"              space=^1
yabai -m rule --add app="^Discord$"             space=^2
yabai -m rule --add app="^FaceTime$"            space=^2
yabai -m rule --add app="^Mail$"                space=^2
yabai -m rule --add app="^Messages$"            space=^2
yabai -m rule --add app="^Signal$"              space=^2
yabai -m rule --add app="^Figma$"               space=^3
yabai -m rule --add app="^iTerm$"               space=^3
yabai -m rule --add app="^Terminal$"            space=^3
yabai -m rule --add app="^VSCodium$"            space=^3
yabai -m rule --add app="^Calendrier$"          space=^4
yabai -m rule --add app="^Contacts$"            space=^4
yabai -m rule --add app="^Obsidian$"            space=^4
yabai -m rule --add app="^Rappel$"              space=^4
yabai -m rule --add app="^Infuse$"              space=^5
yabai -m rule --add app="^Musique$"             space=^5
yabai -m rule --add app="^VLC$"                 space=^5
yabai -m rule --add app="^Finder$"              space=^6
yabai -m rule --add app="^KeePassXC$"           space=^6
yabai -m rule --add app="^Préférences$ Système" space=^6 manage=off border=on
yabai -m rule --add app="^Preference$"                   manage=off border=on
yabai -m rule --add app="^Spotlight$"                    manage=off border=on

${SET_SPACE_LABELS}

# Some Settings For Simple-Bar
yabai -m signal --add event=space_changed              action="${SIMPLE_BAR_REFRESH}" label="Refresh simple-bar on space change"
yabai -m signal --add event=space_changed              action="${SIMPLE_BAR_REFRESH}" label="Refresh simple-bar on space change"
yabai -m signal --add event=display_changed            action="${SIMPLE_BAR_REFRESH}" label="Refresh simple-bar on display focus change"
yabai -m signal --add event=window_focused             action="${SIMPLE_BAR_REFRESH}" label="Refresh simple-bar when focused application changes"
yabai -m signal --add event=window_resized             action="${SIMPLE_BAR_REFRESH}" label="Refresh simple-bar when a window is resized"
yabai -m signal --add event=application_front_switched action="${SIMPLE_BAR_REFRESH}" label="Refresh simple-bar when front application switched application changes"
yabai -m signal --add event=window_destroyed           action="${SIMPLE_BAR_REFRESH}" label="Refresh simple-bar when an application window is closed"
yabai -m signal --add event=window_title_changed       action="${SIMPLE_BAR_REFRESH}" label="Refresh simple-bar when current window title changes"
yabai -m signal --add event=space_changed              action="${SET_SPACE_LABELS}"   label="Refresh simple-bar on space creation"

set +x

echo "yabai configuration loaded.."
