#!/bin/zsh

spacebar -m config position                    top
spacebar -m config display                     main
spacebar -m config height                      36
spacebar -m config title                       off
spacebar -m config spaces                      on
spacebar -m config clock                       on
spacebar -m config power                       on
spacebar -m config padding_left                20
spacebar -m config padding_right               20
spacebar -m config spacing_left                25
spacebar -m config spacing_right               25
spacebar -m config text_font                   "JetBrainsMono Nerd Font Mono:Regular:12.0"
spacebar -m config icon_font                   "JetBrainsMono Nerd Font Mono:Regular:12.0"
spacebar -m config background_color            0xffffffff
spacebar -m config foreground_color            0xff000000
spacebar -m config power_icon_color            0xff000000
spacebar -m config battery_icon_color          0xff000000
spacebar -m config dnd_icon_color              0xff000000
spacebar -m config clock_icon_color            0xff000000
spacebar -m config power_icon_strip             
spacebar -m config space_icon                  •
spacebar -m config space_icon_color            0x33000000
spacebar -m config space_icon_color_secondary  0x33000000
spacebar -m config space_icon_color_tertiary   0x33000000
spacebar -m config space_icon_strip            "ﱢ" "msg" "dev" "org" "fun" "utl" "dsn" "msc" "msc"
spacebar -m config spaces_for_all_displays     on
spacebar -m config clock_icon                  
spacebar -m config dnd_icon                    
spacebar -m config clock_format                "%d/%m/%y %R"
spacebar -m config right_shell                 off
spacebar -m config right_shell_icon            
spacebar -m config right_shell_command         "whoami"

echo "spacebar configuration loaded.."
